# Change these first
owner: mkopec # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Authentication service
    url: https://auth.nozomi.space
  - name: Webmail
    url: https://webmail.nozomi.space
  - name: Matrix
    url: https://matrix.nozomi.space
  - name: Element
    url: https://chat.nozomi.space
  - name: Gitea
    url: https://git.nozomi.space
  - name: Home Assistant
    url: https://hass.nozomi.space
  - name: Audiobookshelf
    url: https://radio.nozomi.space
  - name: Immich
    url: https://photos.nozomi.space
  - name: Jellyfin
    url: https://media.nozomi.space

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.nozomi.space
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "nozomi.space services status"
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
